node {
    def server = Artifactory.server "playtika"
    def rtPip = Artifactory.newPipBuild()
    def buildInfo
    //def virtual_env_activation = "source /Users/myUser/venv-example/bin/activate" // pip virtual-environment activation command

    stage ('Clone') {
	checkout scm
    }

    stage ('Artifactory configuration') {
        rtPip.resolver repo: 'default-pypi', server: server
        buildInfo = Artifactory.newBuildInfo()
    }

    stage ('Pip install') {
        rtPip.install buildInfo: buildInfo, args: "-r requirements.txt" //, envActivation: virtual_env_activation
    }

    stage ('Package and create distribution archives') {
        sh '''
            //$virtual_env_activation
            python setup.py sdist bdist_wheel
        '''
    }

    stage ('Upload packages') {
        def uploadSpec = """{
            "files": [
                {
                    "pattern": "dist/",
                    "target": "pypi-virtual/"
                }
            ]
        }"""
        server.upload buildInfo: buildInfo, spec: uploadSpec
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}
